#/oregen reload 로 리로드 가능합니다.
TriggerBlocks: #아이템 에더 블럭도 트리거로 작동합니다. (test:test 대소문자 구분 필요 namespace도 같이 적어주세요)
  OAK_FENCE: NORMAL
  DARK_OAK_FENCE: EPIC
  #test:test: NORMAL
OreGens: #총합 100
  NORMAL:
    VANILLA:
      STONE: 24.95
      DEEPSLATE: 17.00
      COAL_ORE: 8.00
      DEEPSLATE_COAL_ORE: 8.00
      COPPER_ORE: 7.00
      DEEPSLATE_COPPER_ORE: 7.00
      IRON_ORE: 6.00
      DEEPSLATE_IRON_ORE: 6.00
      GOLD_ORE: 4.50
      DEEPSLATE_GOLD_ORE: 4.50
      DIAMOND_ORE: 2.00
      DEEPSLATE_DIAMOND_ORE: 2.00
      EMERALD_ORE: 1.00
      DEEPSLATE_EMERALD_ORE: 1.00
      ANCIENT_DEBRIS: 1.05
    ITEMADDER: #대소문자 구분 필요
      #test: 0.05
      
  EPIC:
    VANILLA:
      STONE: 18.95
      DEEPSLATE: 14.00
      COAL_ORE: 8.00
      DEEPSLATE_COAL_ORE: 8.00
      COPPER_ORE: 7.00
      DEEPSLATE_COPPER_ORE: 7.00
      IRON_ORE: 6.00
      DEEPSLATE_IRON_ORE: 6.00
      GOLD_ORE: 4.50
      DEEPSLATE_GOLD_ORE: 4.50
      DIAMOND_ORE: 4.00
      DEEPSLATE_DIAMOND_ORE: 4.00
      EMERALD_ORE: 3.00
      DEEPSLATE_EMERALD_ORE: 3.00
      ANCIENT_DEBRIS: 2.05
    ITEMADDER:
      #test: 0.05