name: OrgGen
version: '1.0-SNAPSHOT'
author: hunseong
main: org.florastudio.OreGen.OreGen
api-version: '1.21'
description: fence + water ore generator
depend:
  - ItemsAdder
commands:
  oregen:
    description: OreGen 설정을 리로드합니다.
    usage: /<command>